---
version: 1
enabled: true
template_file: .stoat/template.hbs
plugins:
  job_runtime:
    enabled: false
  static_hosting:
    video_preview:
      metadata:
        name: "Video Preview"
      path: out/video.mp4
